apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-list-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-list-clusterrole
subjects:
- kind: ServiceAccount
  name: codeflare-operator-controller-manager
  namespace: openshift-operators
