# This workflow will build an image for the instascale-controller, then push the image to the `project-codeflare` quay repo

name: Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "custom-nb-image/VERSION"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Grab New Version Tag
      run: |
        echo "tag=$(cat custom-nb-image/VERSION)" >> $GITHUB_ENV

    - name: Image Build
      run: |
        cd custom-nb-image
        docker build -t quay.io/project-codeflare/notebook:${{ env.tag }} .
        docker tag quay.io/project-codeflare/notebook:${{ env.tag }} quay.io/project-codeflare/notebook:latest

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Image Push
      run: |
        docker push quay.io/project-codeflare/notebook:${{ env.tag }}
        docker push quay.io/project-codeflare/notebook:latest
